### ISSUE TITLE
Rated Function Fires on all instances

### ISSUE THREAD

**Issue by selected-pixel-jameson** [akempes/angular-rateit#15]
Hey just looking for some help here. I have this implemented in a ng-repeat and have the rated attribute pointing to a function on my controller, I.e. vm.postRating(item). When this fires it fires for every item in the collection of items that are contained within the my-repeat. Seems like it should just fire for the item that has just been rated. Not sure if I'm doing something wrong or not. Seems pretty straight forward.

**Comment by kostaskol** [comment]
I suppose you have something like this:
```JavaScript
<div ng-repeat="item in items">
       <ng-rate-it ... rated="myRatingFunc()"></ng-rate-it>
</div>
```
You can clearly see that the "myRatingFunc" will have absolutely no idea as to which item has actually been rated.
You can change your code to the following
```JavaScript
<div ng-repeat="item in items">
       <ng-rate-it ... rated="myRatingFunc($index)"></ng-rate-it>
</div>
```

and in your controller:
```JavaScript
$scope.myRatingFunc = function(index) {
       var ratedItem = $scope.items[index];
       .... // Do what you will with that item
}```

**Comment by akempes** [comment]
@selected-pixel-jameson Sorry that it took my so long to respond to your question. I've just published a new release and updated the documentation. If you still have some trouble please let me know!
