### ISSUE TITLE
Readonly Rating Becomes Writeable in Version 2.0.3

### ISSUE THREAD

**Issue by edmondchui** [akempes/angular-rateit#4]
After upgrading to version 2.0.3, my original read-only rating suddenly becomes writable.

Note: It works fine when I was only including the change from pull-request #1.

**Comment by akempes** [comment]
Please check the example files. There is a read only example documented. I just added also a dynamic read only example to the master branch example folder.

**Comment by edmondchui** [comment]
Thanks for the example.

What actually happened was I had been using the HTML attribute `readonly` before version 2.0.3 and it had been working find. According to the example, I need to use `read-only` now. After changing the attribute name it works fine.

Thanks again!
