### ISSUE TITLE
Not support AngularJS v1.2.26?

### ISSUE THREAD

**Issue by tuanjihoo** [akempes/angular-rateit#7]
i use on AngularJS v1.2.26. but, it's not working

**Comment by akempes** [comment]
Thanks for your message!
I did some tests and found the problem. Please try  <div ng-rate-it ng-model="model.basic"></div>

I will update the documentation soon!

Tanks!

**Comment by akempes** [comment]
@tuanlibra I just noticed that a part of my message is missing... When you use `<div ng-rate-it ng-model="test.rateit"></div>` it will work in angular 1.2.\* I'm about to update the documentation about this issue.

Sorry for the inconvenience!
